kind: Deployment
apiversion: apps/v1 
metadata:
  name : app  
  lables :
    app: myapp
spec:
  selector: 
    matchLabels:
      app: fe  
  replicas: 50   
  template:
    metadata:
      name: webapp    
      labels:
        app: fe    
    spec:
      containers:
      - name: app 
        image: fintech/wfapp:v1  
        ports:
        - containerPort: 8080 
---
kind: Service 
apiversion: v1  
metadata :
  name: mysvc
spec:
  type: NodePort 
  selector:
    app: fe
  ports:
  - ports : 80  
  - targetPort: 8080
  - nodePort: 31000 #[30000 to 32767] 
