- hosts: docker
  tasks:
  - name: copyfile
    copy: src=Dockerfile dest=/home/ubuntu
  - name:
    copy:
      src: target
      dest: /home/ubuntu
  - name: build8
    shell: docker build -t fintech/wfapp:v1 .
  - name: push  
    shell: docker push fintech/wfapp:v1 
  - name: delete image  
    shell: docker rmi -f fintech/wfapp:v1
--- 
- hosts: k8s  
  tasks: 
    - name: copy deployment manifest files   
      copy: src=app.yml dest=/home/ubuntu/myapp.yml    
    - name: deploy the web application 
      shell: kubectl apply -f /home/ubuntu/myapp.yml  

